name: CI Tests

on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup dependencies
      run: |
          sudo apt update
          sudo apt install -y lcov libsqlite3-dev liblz4-dev libuv1-dev

    - name: Build raft
      run: |
          git clone https://github.com/cowsql/raft.git --depth 1
          cd raft
          autoreconf -i
          ./configure --enable-debug --enable-sanitize
          make -j4
          sudo make install
          sudo ldconfig
          cd ..

    - name: Build cowsql
      run: |
          autoreconf -i
          ./configure --enable-debug --enable-code-coverage --enable-sanitize
          make CFLAGS=-O0 -j2

    - name: Test
      run: |
           make CFLAGS=-O0 -j2 check || (cat ./test-suite.log && false)

    - name: Coverage
      run: make code-coverage-capture

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true
